version: "3"

services:
  sonarqube:
    image: sonarqube:8.2-community
    container_name: sonarqube
    hostname: sonarqube
    expose:
      - 9000
    user: "999"
    ports:
      - 9000:9000
    networks:
      - sonarnet
    environment:
    - sonar.jdbc.username=sonar
    - sonar.jdbc.password=sonar
    - sonar.jdbc.url=jdbc:postgresql://db/sonar
    - sonar.search.javaAdditionalOpts=-Dbootstrap.system_call_filter=false
    volumes:
      - ./sonarqube/logs:/opt/sonarqube/logs
      - ./sonarqube/data:/opt/sonarqube/data
      - ./sonarqube/extensions:/opt/sonarqube/extensions

  db:
    image: postgres:12.0
    container_name: sonarqube-pg
    hostname: sonarqube-pg
    networks:
      - sonarnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - ./postgresql:/var/lib/postgresql
      # - ./postgresql/data:/var/lib/postgresql/data

networks:
  sonarnet: